name: Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy comprehensive scan
        run: |
          docker run --rm -v $(pwd):/project aquasec/trivy:latest \
            fs --scanners vuln,secret,misconfig \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            /project
