name: TruffleHog Security Scan
on:
  pull_request:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TruffleHog Scan
        run: |
          docker run --rm -v "$PWD:/scan" \
            ghcr.io/trufflesecurity/trufflehog:latest \
            filesystem /scan --fail --only-verified